aws:
  sqs:
    accessKey: "${aws_sqs_accessKey}"
    secretKey: "${aws_sqs_secretKey}"
    region: "${aws_sqs_region}"
    queues:
      book_purchase: "arn:aws:sqs:us-east-1:843981437160:book_purchase"
      book_restock: "arn:aws:sqs:us-east-1:843981437160:book_restock"
